server:
  port: 8110

spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-h2/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:file:./todo
    username: sa
    password: ZSE4zse4
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
