server:
  port: 8110

spring:
  profiles:
    active: h2
    default: h2

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
  endpoint:
    health:
      show-details: ALWAYS